import asyncpg

from harle_utils import InvalidDatabaseSchemaError

REQUIRED_COLUMNS = frozenset(
    {
        "assistant_profiles.created_at",
        "assistant_profiles.display_name",
        "assistant_profiles.interaction_frequency",
        "assistant_profiles.profile_text",
        "assistant_profiles.updated_at",
        "assistant_profiles.user_id",
        "conversations.completed_at",
        "conversations.created_at",
        "conversations.failure_code",
        "conversations.id",
        "conversations.kind",
        "conversations.model",
        "conversations.prompt",
        "conversations.response",
        "conversations.status",
        "conversations.telegram_chat_id",
        "conversations.telegram_update_id",
        "conversations.tool_interaction_index",
        "conversations.tool_call_response",
        "conversations.tool_result",
        "conversations.user_id",
        "expense_transactions.amount",
        "expense_transactions.category",
        "expense_transactions.created_at",
        "expense_transactions.currency",
        "expense_transactions.description",
        "expense_transactions.entry_type",
        "expense_transactions.id",
        "expense_transactions.installment_count",
        "expense_transactions.installment_group_id",
        "expense_transactions.installment_number",
        "expense_transactions.transaction_date",
        "expense_transactions.updated_at",
        "expense_transactions.user_id",
        "event_notification_deliveries.delivered_at",
        "event_notification_deliveries.event_id",
        "event_notification_deliveries.id",
        "event_notification_deliveries.notification_window_start",
        "event_notification_deliveries.occurrence_starts_at",
        "event_notification_deliveries.user_id",
        "event_notification_quota_notices.attempted_at",
        "event_notification_quota_notices.delivered_at",
        "event_notification_quota_notices.period_starts_at",
        "event_notification_quota_notices.status",
        "event_notification_quota_notices.user_id",
        "external_identities.created_at",
        "external_identities.display_name",
        "external_identities.email",
        "external_identities.external_user_id",
        "external_identities.id",
        "external_identities.provider",
        "external_identities.updated_at",
        "external_identities.user_id",
        "internal_events.all_day",
        "internal_events.created_at",
        "internal_events.description",
        "internal_events.ends_at",
        "internal_events.event_type",
        "internal_events.id",
        "internal_events.last_notified_at",
        "internal_events.notification_window_start",
        "internal_events.recurrence_rule",
        "internal_events.starts_at",
        "internal_events.status",
        "internal_events.timezone",
        "internal_events.title",
        "internal_events.updated_at",
        "internal_events.user_id",
        "interaction_events.created_at",
        "interaction_events.id",
        "interaction_events.last_agent_message_at",
        "interaction_events.last_user_message_at",
        "interaction_events.status",
        "interaction_events.updated_at",
        "interaction_events.user_id",
        "plans.active",
        "plans.billing_interval",
        "plans.code",
        "plans.created_at",
        "plans.currency",
        "plans.display_name",
        "plans.monthly_price_ars",
        "plans.monthly_notification_limit",
        "plans.monthly_request_limit",
        "plans.updated_at",
        "payment_subscriptions.cancel_at_period_end",
        "payment_subscriptions.checkout_url",
        "payment_subscriptions.created_at",
        "payment_subscriptions.id",
        "payment_subscriptions.latest_payment_at",
        "payment_subscriptions.latest_payment_updated_at",
        "payment_subscriptions.next_payment_at",
        "payment_subscriptions.payer_email",
        "payment_subscriptions.period_ends_at",
        "payment_subscriptions.period_starts_at",
        "payment_subscriptions.plan_code",
        "payment_subscriptions.provider",
        "payment_subscriptions.provider_status",
        "payment_subscriptions.provider_subscription_id",
        "payment_subscriptions.provider_updated_at",
        "payment_subscriptions.status",
        "payment_subscriptions.updated_at",
        "payment_subscriptions.user_id",
        "payment_webhook_claims.processed_at",
        "payment_webhook_claims.provider_event_id",
        "payment_webhook_claims.provider_request_id",
        "payment_webhook_claims.received_at",
        "payment_webhook_claims.resource_id",
        "payment_webhook_claims.status",
        "payment_webhook_claims.topic",
        "subscription_payments.amount",
        "subscription_payments.created_at",
        "subscription_payments.currency",
        "subscription_payments.debit_at",
        "subscription_payments.id",
        "subscription_payments.provider_invoice_id",
        "subscription_payments.provider_payment_id",
        "subscription_payments.status",
        "subscription_payments.subscription_id",
        "subscription_payments.updated_at",
        "telegram_update_claims.claimed_at",
        "telegram_update_claims.conversation_id",
        "telegram_update_claims.delivered_at",
        "telegram_update_claims.message_text",
        "telegram_update_claims.status",
        "telegram_update_claims.telegram_chat_id",
        "telegram_update_claims.telegram_user_id",
        "telegram_update_claims.tool_started_at",
        "telegram_update_claims.update_id",
        "telegram_update_claims.updated_at",
        "telegram_link_tokens.consumed_at",
        "telegram_link_tokens.created_at",
        "telegram_link_tokens.expires_at",
        "telegram_link_tokens.id",
        "telegram_link_tokens.token_hash",
        "telegram_link_tokens.user_id",
        "user_profiles.created_at",
        "user_profiles.latitude",
        "user_profiles.locale",
        "user_profiles.longitude",
        "user_profiles.personal_history",
        "user_profiles.preferred_name",
        "user_profiles.timezone",
        "user_profiles.updated_at",
        "user_profiles.user_id",
        "users.created_at",
        "users.display_name",
        "users.id",
        "users.plan_code",
        "users.subscription_status",
        "users.subscription_synced_at",
        "users.subscription_period_ends_at",
        "users.subscription_period_starts_at",
        "users.subscription_valid_until",
        "users.updated_at",
        "web_sessions.created_at",
        "web_sessions.expires_at",
        "web_sessions.id",
        "web_sessions.last_used_at",
        "web_sessions.revoked_at",
        "web_sessions.session_token_hash",
        "web_sessions.user_id",
    },
)


async def validate_postgres_schema(pool: asyncpg.Pool) -> None:
    table_names = sorted(
        {column.split(".", maxsplit=1)[0] for column in REQUIRED_COLUMNS},
    )
    async with pool.acquire() as connection:
        rows = await connection.fetch(
            """
            SELECT table_name, column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
                AND table_name = ANY($1::text[])
            """,
            table_names,
        )

    available_columns = {
        f"{_text(row, 'table_name')}.{_text(row, 'column_name')}" for row in rows
    }
    missing_columns = sorted(REQUIRED_COLUMNS - available_columns)
    if missing_columns:
        missing = ", ".join(missing_columns)
        raise InvalidDatabaseSchemaError(
            f"PostgreSQL schema is missing required columns: {missing}",
        )


def _text(row: asyncpg.Record, key: str) -> str:
    value: object = row[key]
    if not isinstance(value, str):
        raise TypeError(f"Expected {key} to be text.")
    return value
